const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..');
const app={innerHTML:'',querySelector(){return null;},querySelectorAll(){return[];},insertAdjacentHTML(_p,h){this.innerHTML+=h;},appendChild(){}};
const storage=new Map();
const classList={add(){},remove(){},contains(){return false;}};
const document={documentElement:{classList},getElementById(id){return id==='app'?app:null;},querySelector(){return null;},querySelectorAll(){return[];},createElement(){return{className:'',textContent:'',remove(){},style:{},appendChild(){},querySelector(){return null;},querySelectorAll(){return[];}};},body:{appendChild(){},classList}};
class MutationObserver{constructor(cb){this.cb=cb;}observe(){}disconnect(){}}
const windowObj={localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},location:{origin:'http://localhost',href:'http://localhost/index.html'},addEventListener(){},removeEventListener(){},devicePixelRatio:1};
const context={console,Math,Date,Intl,JSON,Number,String,Array,Object,Set,Map,Promise,setTimeout(fn){if(typeof fn==='function')fn();return 0;},clearTimeout(){},document,app,window:windowObj,MutationObserver,fetch:async url=>{const p=path.join(root,String(url).replace(/^\.\//,''));return fs.existsSync(p)?{ok:true,status:200,json:async()=>JSON.parse(fs.readFileSync(p,'utf8')),text:async()=>fs.readFileSync(p,'utf8')}:{ok:false,status:404,json:async()=>({}),text:async()=>''};}};
context.globalThis=context;vm.createContext(context);
const files=['data.js','v024-data.js','gpx-stage-data.js','gpx-engine.js','game.js','v024-expansion.js','historical-manifest.js','current-2026-major.js','staff-database.js','historical-engine.js','staff-market-v026.js','youth-market-v026.js','v026-management.js','v026-frontoffice.js','gpx-integration-v027.js','stage-lab-integration-v027.js','v027.js','v028.js','v029-data.js','v029-club.js'];
for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f,timeout:120000});
const run=code=>vm.runInContext(code,context,{timeout:120000});
const check=(v,m)=>{if(!v)throw new Error(m)};
(async()=>{
  check(app.innerHTML.includes('¿Qué tipo de juego quieres iniciar?'),'No abre el asistente inicial');
  check(run('v029Diagnostics().version')==='v0.29.1-club-hq-hotfix','No inicializa v0.29');
  check(run('V029_HEADQUARTERS.length')>=15,'Catálogo de sedes incompleto');
  check(run('V029_FACILITIES.length')===10,'Instalaciones incompletas');
  check(run('V029_SPONSOR_COMPANIES.length')>=50,'Mercado de patrocinadores insuficiente');
  check(run('FULL_2026_PACK_V026.teams.length')===34,'Se pierde la base 2026');
  check(run('FULL_2026_PACK_V026.riders.length')===927,'Se pierden corredores 2026');
  check(run('STAFF_MARKET_V026.length')===1000,'Se pierde mercado staff');
  check(run('YOUTH_MARKET_V026.length')===1000,'Se pierde mercado U23');
  check(run("typeof renderStageLabSetup==='function' && typeof gpxPointAtKm==='function'"),'Se pierde Stage Lab/GPX');

  await run("chooseGameModeV026('single')");
  const raceId=run('V026Runtime.catalogRaces[0].id');
  run(`chooseSingleRaceV026(${JSON.stringify(raceId)})`);
  await run('continueCompetitionV026()');
  run("selectTeam('uae')");
  check(run('Game.stageLab.screenActive'),'Stage Lab no se abre');
  run('skipStageLabForCurrentRace()');
  check(app.innerHTML.includes('Define la sede y el ADN del club'),'No aparece onboarding de sede');
  check(run('ensureV029State().onboardingConfirmed')===false,'Onboarding marcado prematuramente');
  run("v029SelectInitialHQ('girona')");
  run("ensureV029State().brand.identityId='technology';renderRosterSelection()");
  run('v029ConfirmOnboarding()');
  check(app.innerHTML.includes('Selecciona 8 corredores'),'No avanza a convocatoria');
  check(run('ensureV029State().headquarters.cityId')==='girona','No guarda la sede');
  check(run('ensureV029State().brand.identityId')==='technology','No guarda identidad');
  run('confirmRoster()');
  check(run('Game.rosterLocked'),'No confirma convocatoria');
  run("setTab('club_hq')");
  check(app.innerHTML.includes('CLUB HEADQUARTERS'),'No renderiza módulo Club HQ');
  check(app.innerHTML.includes('Patrocinadores'),'No renderiza navegación comercial');
  const cashBefore=run('v029ClubCash()');
  run("v029StartFacilityProject('commercial_media')");
  check(run("ensureV029State().campus.projects.some(p=>p.facilityId==='commercial_media')"),'No inicia construcción');
  check(run('v029ClubCash()')<cashBefore,'La obra no descuenta caja');
  run("v029SetClubSection('sponsors')");
  check(app.innerHTML.includes('MERCADO DE PATROCINIO'),'No renderiza ofertas');
  const offerId=run("ensureV029State().sponsors.offers.find(o=>o.type==='secondary').id");
  run(`v029AcceptOffer(${JSON.stringify(offerId)})`);
  check(run("ensureV029State().sponsors.contracts.some(c=>c.id==="+JSON.stringify(offerId)+")"),'No acepta patrocinador');
  run("setTab('director')");
  run('simulateFullStageQuick()');
  check(run('Game.lastStage.results.length')>0,'Simulación sin resultados');
  check(!run('Game.lastStage.results.some(x=>!Number.isFinite(x.time))'),'Tiempos inválidos');
  run('finishRace()');
  check(run('ensureV029State().media.history.length')>=1,'No registra exposición postcarrera');
  check(run('v029Diagnostics().clubValue')>0,'Valor de club inválido');
  run('saveGame(false)');
  check(storage.has('cyclingManager_v029_club_hq_sponsors'),'No crea guardado v0.29');
  const savedCash=run('v029ClubCash()');
  run("Game.manager.budget=1;ensureV029State().headquarters.cityId='dubai'");
  await run('loadGame()');
  check(run('v029ClubCash()')===savedCash,'La carga no restaura la caja v0.29');
  check(run('ensureV029State().headquarters.cityId')==='girona','La carga no restaura la sede v0.29');
  console.log(JSON.stringify({ok:true,version:run('v029Diagnostics().version'),hq:run('ensureV029State().headquarters.cityId'),facilities:run('V029_FACILITIES.length'),offers:run('ensureV029State().sponsors.offers.length'),contracts:run('ensureV029State().sponsors.contracts.length'),clubValue:run('v029ClubValue()'),teams:run('FULL_2026_PACK_V026.teams.length'),riders:run('FULL_2026_PACK_V026.riders.length')},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
